# Generated by Django 3.0.5 on 2021-05-22 01:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='Customer', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('confirmation_number', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
