# This is a basic workflow to help you get started with Actions

name: Mirroring

on: push

jobs:
  to_internal:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      # 02f1627ade9e6b3b69e6a6d4fe8bc997474f48d1 is v1
      # we use the ref to avoid supply chain attacks
    - uses: pixta-dev/repository-mirroring-action@02f1627ade9e6b3b69e6a6d4fe8bc997474f48d1
      with:
        target_repo_url:
          git@github.com:Flatbook/sliced_bread-private.git
        ssh_private_key:
          ${{ secrets.PRIVATE_SLICED_BREAD_SSH_KEY }}
